spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
aws:
  s3:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${S3_BUCKET}
    region: ap-northeast-2