spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourevents
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

app:
  server:
    url: http://localhost:8080
