name: 테스트 통과 여부 검사

on:
  pull_request:
    branches: [ "main" ]

jobs:
  runs-on: ubuntu-22.04

  build:
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      - name: Gradle 테스트
        run: ./gradlew --info test

  show-test:
    steps:
      - name: Test 결과 출력
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'
